### ISSUE TITLE
大佬，侧滑之后，侧滑按钮那个位置还有点击事件怎么解决

### ISSUE THREAD

**Issue by xiaoxiaolyt** [WangcWj/WeSwipe#13]
我设置了一个删除、一个置顶，侧滑恢复之后，点那个位置还是会触发删除或者置顶的点击事件，怎么隐藏那两个按钮呢

**Comment by WangcWj** [comment]
最简单的就是 给Item设置个点击事件拦截下。。。这个 我还没处理

**Comment by xiaoxiaolyt** [comment]
好吧。。

**Comment by WangcWj** [comment]
我 这周改一版 把这些功能都给完善一下

**Comment by WangcWj** [comment]
这个问题，是这样的：  侧滑布局覆盖侧滑菜单这种类型的话，点击事件是会穿透的，也就是点击侧滑布局的时候，如果你的侧滑布局不拦截或者消费事件，事件就会传递到子View中，这时你的侧滑菜单又设置了点击事件，所以就会执行你的 删除、置顶操作。所以，框架的层面不能侵入用户的布局，这个问题就要自行找个方法屏蔽下了。
