### ISSUE TITLE
如果item的最外层的高度不是写死的话那么里面不管什么设置好像没有效果

### ISSUE THREAD

**Issue by c040926** [WangcWj/WeSwipe#2]
如果item的最外层的高度不是写死的话那么里面不管什么设置好像就是会自适应,就是不能充满整个条目高度,
还有PlusItemSlideCallback这个类下面的onChildDraw这里面需要用到这个Adapt的对象,这个对象能不能通过set来设置而不是这样绑定写死,如果我其他地方还要用到这个侧滑那不是还要在写一个这个方法

**Comment by WangcWj** [comment]
那个CallBack里面的adapter可以用set设置的  其实很灵活的  代码也比较能看懂  你想到能换的地方基本都能换

**Comment by WangcWj** [comment]
> 如果item的最外层的高度不是写死的话那么里面不管什么设置好像就是会自适应,就是不能充满整个条目高度,
> 还有PlusItemSlideCallback这个类下面的onChildDraw这里面需要用到这个Adapt的对象,这个对象能不能通过set来设置而不是这样绑定写死,如果我其他地方还要用到这个侧滑那不是还要在写一个这个方法

你好! 才深入的看到这个问题,PlusItemSlideCallback的onChildDraw()方法里面可以写成set的但是有一点就是你所有的adapter就得实现里面的一个统一的接口了...这样确实是可以更简单一点!
