### ISSUE TITLE
侧滑删除了一个item，下一个item的ui会变成侧滑打开的状态

### ISSUE THREAD

**Issue by lbw718733550** [WangcWj/WeSwipe#3]
侧滑删除了一个item，下一个item的ui会变成侧滑打开的状态

**Comment by lbw718733550** [comment]
在 onBindViewHolder  holder.textView.setTranslationX(0); 好像就可以了

**Comment by WangcWj** [comment]
已经 解决了啊    那个是item的状态复用  所以我一般都是 侧滑删除之后 就把所有的都关掉
